default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: hipstarter_development

test:
  <<: *default
  database: hipstarter_test

production:
  <<: *default
  database: hipstarter_production
  username: hipstarter
  password: <%= ENV['HIPSTARTER_DATABASE_PASSWORD'] %>
